### ISSUE TITLE
[FEATURE] Log creating / deleting Items

### ISSUE THREAD

**Issue by IrishWolf** [Larkinabout/fvtt-change-log#12]
**Describe your idea**
Would it be possible in the future to log the creation or deletion of items for an actor?
Like the actor gets a new item or looses it.

Maybe I'm blind but I think I didn't see that option.

**Comment by hkchang16** [comment]
bump on this! I'd love to see changes to inventory, not just quantities of items.

Love the module!!

**Comment by Larkinabout** [comment]
Should be possible. I'll have a look into it.

**Comment by IrishWolf** [comment]
Thanks for adding it!
