### ISSUE TITLE
[FEATURE] Show the difference in the change

### ISSUE THREAD

**Issue by GambetTV** [Larkinabout/fvtt-change-log#13]
Right now when a value changes (such as hit points), your module will show the original amount and the new amount. So if someone takes 5 points of damage, it might show 80 > 75. This is generally fine, but I do run into an awful lot of scenarios where damage automation goes wrong, maybe there's a bug, maybe a spell is configured wrong, maybe a player forgot to unselect their targets from last turn, and now suddenly 15 characters took damage that weren't supposed to. In a situation like that, it would really help me to see what the difference in value was, so that I can, at a glance, tell if any character took half or double damage from damage resistances/vulnerabilities, or what have you.

I'm wondering if it would be possible to change the output to include this number, so for instance, in the above scenario, the output might say: 80 > -5 > 75 or something to that effect.

**Comment by Larkinabout** [comment]
Yes, will be easy enough. I'll probably add it as optional.

**Comment by Larkinabout** [comment]
Added in 1.1.0.
