### ISSUE TITLE
[FEATURE] warlock spell slots

### ISSUE THREAD

**Issue by Nikakto** [Larkinabout/fvtt-change-log#2]
**Describe your idea**
No options to track warlock spells slots. Changing of it does not emit new message.

**Versions**
- Change Log: [e.g. 1.0.0]
- System: [e.g. dnd5e 2.0.0]
- Foundry VTT: [e.g. 11.305]

**Additional context**
Logging to separate chat/window is great feature too).
upd: You can use existing module for chat: https://foundryvtt.com/packages/chat-tabs
You just need to set type of log messages

**Comment by Larkinabout** [comment]
Fixed in Change Log 0.5.0.

**Comment by Nikakto** [comment]
Wow. It was fast!)
