### ISSUE TITLE
[FEATURE] Support Customizable Chat Tabs Module

### ISSUE THREAD

**Issue by Larkinabout** [Larkinabout/fvtt-change-log#3]
**Describe your idea**
Add support for the **Customizable Chat Tabs** module to allow logs to be displayed in a separate tab. See #2 and mclemente/fvtt-chat-tabs/issues/3

**Comment by Nikakto** [comment]
https://github.com/mclemente/fvtt-chat-tabs/pull/5

**Comment by mclemente** [comment]
I just accepted that PR, so you might be able to use it.

**Comment by Larkinabout** [comment]
Added in Change Log 0.8.0.
